directory: ~/music 
library: ~/.config/beets/library.db
plugins: convert duplicates embedart fetchart fromfilename 

import:
  move: yes

convert:
  copy_album_art: yes
  dest: ~/Downloads/Music

embedart:
  ifempty: yes
  remove_art_file: yes
